### ISSUE TITLE
[HDBTI] Add support for ~

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#1110]
HDBTI files where the `~` symbol is used as **delimField** are not processed and since no records are inserted in the respective table:

**file.csv**:
```csv
Column1~Column2~Column3
101~ABCD~Text1234
101~QWER~Text5678
102~QAZW~Abcd1234
```

**Table1.hdbti**:

```yaml
import = [
  {
    table = "test::Table1"; 
    schema = "DBADMIN";
    file = "test:file.csv";
    header = true; 
    useHeaderNames = true;
    delimField = "~"; 
    delimEnclosing= "\"";
  }
];
```

**Exception:**
```java
2022-01-27 15:58:00.781 [ERROR] [pool-10346-thread-1] c.s.x.h.s.XSKTableImportSynchronizer - An error occurred while trying to execute import. Only ';' or ',' characters are supported as delimiters for csv files.
com.sap.xsk.hdbti.api.XSKTableImportException: Only ';' or ',' characters are supported as delimiters for csv files.
	at com.sap.xsk.hdbti.processors.XSKHDBTIProcessor.createCSVFormat(XSKHDBTIProcessor.java:178) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdbti.processors.XSKHDBTIProcessor.getCsvParser(XSKHDBTIProcessor.java:158) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdbti.processors.XSKHDBTIProcessor.process(XSKHDBTIProcessor.java:72) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdbti.synchronizer.XSKTableImportSynchronizer.executeTableImport(XSKTableImportSynchronizer.java:246) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdbti.synchronizer.XSKTableImportSynchronizer.reimportAffectedHdbtiFiles(XSKTableImportSynchronizer.java:167) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdbti.synchronizer.XSKTableImportSynchronizer.lambda$synchronizeResource$0(XSKTableImportSynchronizer.java:156) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
	at com.sap.xsk.hdbti.synchronizer.XSKTableImportSynchronizer.synchronizeResource(XSKTableImportSynchronizer.java:156) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:107) ~[dirigible-core-scheduler-6.1.20.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.20.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.20.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.20.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.20.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.20.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.20.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.20.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeRegistry(AbstractSynchronizer.java:91) ~[dirigible-core-scheduler-6.1.20.jar:na]
	at com.sap.xsk.hdbti.synchronizer.XSKTableImportSynchronizer.synchronize(XSKTableImportSynchronizer.java:93) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizerJob$1.run(AbstractSynchronizerJob.java:52) ~[dirigible-core-scheduler-6.1.20.jar:na]
	at org.eclipse.dirigible.commons.timeout.TimeLimited$1.call(TimeLimited.java:38) ~[dirigible-commons-timeout-6.1.20.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

_**Note:**_ The current workaround is to replace the `~` symbol with a supported one (e.g. `;`)

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
