### ISSUE TITLE
[HDBTI] Double processing of already imported data

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#1114]
**Unpublish** and then **Publish** of already processed HDBTI (data is already imported into the target table) leads to the following exception:

```java
c.s.x.h.service.XSKHDBTICoreService - Error occurred while processing test:file.csv for table test::Table1 at record 40
com.sap.db.jdbc.exceptions.SQLIntegrityConstraintViolationExceptionSapDB: [301]: unique constraint violated: Table(test::Table1), Index(_SYS_TREE_CS_#164285_#0_#P0) with error: unique constraint violation on pos=0 for table H00::DBADMIN:test::Table1en, key=0300000031303104000000455a45310400000053434143 already exists as udiv=40; indexname=_SYS_TREE_CS_#164285_#0_#P0
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:177) ~[ngdbc-2.11.14.jar:na]
	at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42) ~[ngdbc-2.11.14.jar:na]
	at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:841) ~[ngdbc-2.11.14.jar:na]
	at com.sap.db.jdbc.packet.HReplyPacket.getSQLExceptionChain(HReplyPacket.java:158) ~[ngdbc-2.11.14.jar:na]
	at com.sap.db.jdbc.packet.HPartInfo.getSQLExceptionChain(HPartInfo.java:39) ~[ngdbc-2.11.14.jar:na]
	at com.sap.db.jdbc.ConnectionSapDB._receive(ConnectionSapDB.java:4786) ~[ngdbc-2.11.14.jar:na]
	at com.sap.db.jdbc.ConnectionSapDB.exchange(ConnectionSapDB.java:2022) ~[ngdbc-2.11.14.jar:na]
	at com.sap.db.jdbc.PreparedStatementSapDB._execute(PreparedStatementSapDB.java:3063) ~[ngdbc-2.11.14.jar:na]
	at com.sap.db.jdbc.PreparedStatementSapDB._execute(PreparedStatementSapDB.java:2287) ~[ngdbc-2.11.14.jar:na]
	at com.sap.db.jdbc.PreparedStatementSapDB.execute(PreparedStatementSapDB.java:636) ~[ngdbc-2.11.14.jar:na]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at com.sap.xsk.hdbti.dao.XSKCSVRecordDao.executeInsertPreparedStatement(XSKCSVRecordDao.java:157) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdbti.dao.XSKCSVRecordDao.save(XSKCSVRecordDao.java:66) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdbti.service.XSKHDBTICoreService.insertCsvRecords(XSKHDBTICoreService.java:75) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdbti.processors.XSKHDBTIProcessor.process(XSKHDBTIProcessor.java:116) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdbti.synchronizer.XSKTableImportSynchronizer.executeTableImport(XSKTableImportSynchronizer.java:246) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdbti.synchronizer.XSKTableImportSynchronizer.processTableImports(XSKTableImportSynchronizer.java:229) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdbti.synchronizer.XSKTableImportSynchronizer.synchronize(XSKTableImportSynchronizer.java:94) ~[xsk-modules-engines-hdbti-0.13.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizerJob$1.run(AbstractSynchronizerJob.java:52) ~[dirigible-core-scheduler-6.1.20.jar:na]
	at org.eclipse.dirigible.commons.timeout.TimeLimited$1.call(TimeLimited.java:38) ~[dirigible-commons-timeout-6.1.20.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

> _**Note:**_ Such exception is thrown for each record in the CSV file - `c.s.x.h.service.XSKHDBTICoreService - Error occurred while processing test:file.csv for table test::Table1 `**`at record 40`**`

Possible solutions would be:
- **Unpublish** action would actually delete the imported records from the target table - _not really applicable for large data sets_
- Before executing and **INSERT** statement check whether such record already exists with **SELECT** and **UPDATE** if needed - _this would have an impact on the performance_
- Swallow the exception - _log that record already exists with such key_

Related to:
- https://github.com/SAP/xsk/issues/107
- https://github.com/SAP/xsk/issues/540

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
