### ISSUE TITLE
Issue of processing hdbdd file with a long table definition

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1195]
Caused by: org.h2.jdbc.JdbcSQLDataException: Value too long for column "SYNCHRONIZER_ARTEFACT_MESSAGE CHARACTER VARYING(2000)": "'Processing for create hdbprocedure has failed. Create procedure[{""content"":""PRO... (6761)"; SQL statement:
UPDATE "DIRIGIBLE_SYNCHRONIZER_STATE_ARTEFACTS" SET "SYNCHRONIZER_ARTEFACT_NAME" = ?, "SYNCHRONIZER_ARTEFACT_LOCATION" = ?, "SYNCHRONIZER_ARTEFACT_TYPE" = ?, "SYNCHRONIZER_ARTEFACT_STATE" = ?, "SYNCHRONIZER_ARTEFACT_MESSAGE" = ?, "SYNCHRONIZER_ARTEFACT_TIMESTAMP" = ? WHERE ("SYNCHRONIZER_ARTEFACT_ID" = ?) [22001-206]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:525) ~[h2-2.0.206.jar:2.0.206]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:496) ~[h2-2.0.206.jar:2.0.206]
        at org.h2.message.DbException.get(DbException.java:227) ~[h2-2.0.206.jar:2.0.206]

**Comment by dpanayotov** [comment]
@mvmanov could this be related to #1118
