### ISSUE TITLE
[HDBDD] Issue with LocalDate processing

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1200]
**sample.hdbdd**:
```
ENTITY SAMPLE {
    "DATE_OF_BIRTH": String(10);
    "PERSON_CREATED_DATE": LocalDate;
}
```

**Exception**:
```java
c.s.x.h.d.p.t.XSKTableCreateProcessor - CREATE COLUMN TABLE "sample"."SAMPLE" ( "DATE_OF_BIRTH" NVARCHAR (10) , "PERSON_CREATED_DATE" DATE  )
c.s.x.h.d.p.t.XSKTableCreateProcessor - SAP DBTech JDBC: [257]: sql syntax error: unterminated quoted identifier: line 1 col 105 (at pos 105)
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [257]: sql syntax error: unterminated quoted identifier: line 1 col 105 (at pos 105)
        at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:209) ~[ngdbc-2.11.14.jar:na]
        at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42) ~[ngdbc-2.11.14.jar:na]
        at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:841) ~[ngdbc-2.11.14.jar:na]
        at com.sap.db.jdbc.packet.HReplyPacket.getSQLExceptionChain(HReplyPacket.java:158) ~[ngdbc-2.11.14.jar:na]
```

**Comment by dpanayotov** [comment]
caused by 
- #1182
