### ISSUE TITLE
UTCTimestamp in hdbdd

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1203]
ENTITY SAMPLE{
            "CREATED_ON": UTCTimestamp;
    }

2022-02-04 11:10:30.378 [INFO ] [pool-265478-thread-1] c.s.x.h.d.p.t.XSKTableCreateProcessor - Processing Create Table: .....
2022-02-04 11:10:30.398 [ERROR] [pool-265478-thread-1] c.s.x.h.d.p.t.XSKTableCreateProcessor - CREATE COLUMN TABLE "...."."..." ( "CREATED_ON" TIMESTAMP  )
2022-02-04 11:10:30.400 [ERROR] [pool-265478-thread-1] c.s.x.h.d.p.t.XSKTableCreateProcessor - SAP DBTech JDBC: [257]: sql syntax error: unterminated quoted identifier: line 1 col 73 (at pos 73)
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [257]: sql syntax error: unterminated quoted identifier: line 1 col 73 (at pos 73)
        at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:209) ~[ngdbc-2.11.14.jar:na]
        at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42) ~[ngdbc-2.11.14.jar:na]

**Comment by dpanayotov** [comment]
caused by
- #1182
