### ISSUE TITLE
[HDBTable] Wrong format of HDB Table

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#1215]
**sample.hdbtable**
```
table.schemaName = "SAMPLE_1";
table.tableType = COLUMNSTORE;
table.columns = [
    {name = "COL_1"; sqlType = NVARCHAR; nullable = false; length = 256; comment = "Some Comment";},
    {name = "COL_2"; sqlType = NVARCHAR; nullable = false; length = 256; comment = "Some Comment";},
    {name = "COL_3"; sqlType = NVARCHAR; nullable = false; length = 256; comment = "Some Comment";},
    {name = "COL_4"; sqlType = NVARCHAR; nullable = false; length = 5000; comment = "Some Comment";}
];
table.indexes =  [];
table.primaryKey.pkcolumns = ["COL_1", "COL_2", "COL_3"];
```

---

**Problems View**:
- Cause:
    ```
    [@115,544:544=']',<9>,9:18]
    ```
- Expected:
    ```
    mismatched input ']' expecting '{'
    ```

**Exception**:
```java
c.s.x.hdb.ds.facade.XSKHDBCoreFacade - Wrong format of HDB HDB Table: [/sample/sample.hdbtable] during parsing. Ensure you are using the correct format for the correct compatibility version.
com.sap.xsk.exceptions.XSKArtifactParserException: Wrong format of HDB HDB Table: [/sample/sample.hdbtable] during parsing. Ensure you are using the correct format for the correct compatibility version.
	at com.sap.xsk.utils.XSKCommonsUtils.logParserErrors(XSKCommonsUtils.java:124) ~[xsk-modules-engines-commons-0.14.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdb.ds.parser.hdbtable.XSKTableParser.parseHanaXSClassicContent(XSKTableParser.java:103) ~[xsk-modules-engines-hdb-0.14.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdb.ds.parser.hdbtable.XSKTableParser.parse(XSKTableParser.java:82) ~[xsk-modules-engines-hdb-0.14.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdb.ds.parser.hdbtable.XSKTableParser.parse(XSKTableParser.java:57) ~[xsk-modules-engines-hdb-0.14.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdb.ds.service.parser.XSKCoreParserService.parseDataStructure(XSKCoreParserService.java:32) ~[xsk-modules-engines-hdb-0.14.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdb.ds.facade.XSKHDBCoreFacade.parseDataStructureModel(XSKHDBCoreFacade.java:104) ~[xsk-modules-engines-hdb-0.14.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdb.ds.facade.XSKHDBCoreFacade.parseDataStructureModel(XSKHDBCoreFacade.java:120) ~[xsk-modules-engines-hdb-0.14.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdb.ds.facade.XSKHDBCoreFacade.handleResourceSynchronization(XSKHDBCoreFacade.java:125) ~[xsk-modules-engines-hdb-0.14.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdb.ds.synchronizer.XSKDataStructuresSynchronizer.synchronizeResource(XSKDataStructuresSynchronizer.java:408) ~[xsk-modules-engines-hdb-0.14.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:107) ~[dirigible-core-scheduler-6.1.22.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.22.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.22.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.22.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.22.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.22.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.1.22.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeRegistry(AbstractSynchronizer.java:91) ~[dirigible-core-scheduler-6.1.22.jar:na]
	at com.sap.xsk.hdb.ds.synchronizer.XSKDataStructuresSynchronizer.synchronizeRegistry(XSKDataStructuresSynchronizer.java:393) ~[xsk-modules-engines-hdb-0.14.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdb.ds.synchronizer.XSKDataStructuresSynchronizer.synchronize(XSKDataStructuresSynchronizer.java:235) ~[xsk-modules-engines-hdb-0.14.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizerJob$1.run(AbstractSynchronizerJob.java:52) ~[dirigible-core-scheduler-6.1.22.jar:na]
	at org.eclipse.dirigible.commons.timeout.TimeLimited$1.call(TimeLimited.java:38) ~[dirigible-commons-timeout-6.1.22.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

**Comment by ThuF** [comment]
Issue is caused by:
```
table.indexes =  [];
```

It appears that the HDB Table parser is expecting the `table.indexes` to be a map, not an array -> `table.indexes =  {};`

Workaround - delete the `table.indexes` line

**Comment by vmutafov** [comment]
> Issue is caused by:
> 
> ```
> table.indexes =  [];
> ```
> 
> It appears that the HDB Table parser is expecting the `table.indexes` to be a map, not an array -> `table.indexes = {};`
> 
> Workaround - delete the `table.indexes` line

It's caused by `table.indexes = [];` but it should still be an array. The parser fails as it expects the array to have at least one item in it.
