### ISSUE TITLE
[OData] Deployment - issue with keys 

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1359]
org.eclipse.dirigible.core.scheduler.api.SynchronizationException: com.sap.xsk.xsodata.ds.service.XSKOData2TransformerException: 

```java
Keys cannot be specified for source ....... They must only be applied to objects referring a view type
	at com.sap.xsk.xsodata.ds.synchronizer.XSKODataSynchronizer.synchronizeResource(XSKODataSynchronizer.java:250) ~[xsk-modules-engines-xsodata-0.13.8.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:107) ~[dirigible-core-scheduler-6.2.4.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.2.4.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:114) ~[dirigible-core-scheduler-6.2.4.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeRegistry(AbstractSynchronizer.java:91) ~[dirigible-core-scheduler-6.2.4.jar:na]
	at com.sap.xsk.xsodata.ds.synchronizer.XSKODataSynchronizer.synchronizeRegistry(XSKODataSynchronizer.java:223) ~[xsk-modules-engines-xsodata-0.13.8.jar:na]
	at com.sap.xsk.xsodata.ds.synchronizer.XSKODataSynchronizer.synchronize(XSKODataSynchronizer.java:121) ~[xsk-modules-engines-xsodata-0.13.8.jar:na]
	at org.eclipse.dirigible.core.scheduler.synchronizer.OrderedSynchronizer.synchronize(OrderedSynchronizer.java:73) ~[dirigible-core-scheduler-6.2.4.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizerJob$1.run(AbstractSynchronizerJob.java:46) ~[dirigible-core-scheduler-6.2.4.jar:na]
	at org.eclipse.dirigible.commons.timeout.TimeLimited$1.call(TimeLimited.java:38) ~[dirigible-commons-timeout-6.2.4.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: com.sap.xsk.xsodata.ds.service.XSKOData2TransformerException: Keys cannot be specified for source ZAMNSD0030945.VIEWS::CVPRICEREQUESTHEADER. They must only be applied to objects referring a view type
	at com.sap.xsk.xsodata.ds.service.XSKODataParser.applyKeysCondition(XSKODataParser.java:179) ~[xsk-modules-engines-xsodata-0.13.8.jar:na]
	at com.sap.xsk.xsodata.ds.service.XSKODataParser.applyConditions(XSKODataParser.java:130) ~[xsk-modules-engines-xsodata-0.13.8.jar:na]
	at com.sap.xsk.xsodata.ds.service.XSKODataParser.parseXSODataArtifact(XSKODataParser.java:118) ~[xsk-modules-engines-xsodata-0.13.8.jar:na]
	at com.sap.xsk.xsodata.ds.service.XSKODataCoreService.parseOData(XSKODataCoreService.java:104) ~[xsk-modules-engines-xsodata-0.13.8.jar:na]
	at com.sap.xsk.xsodata.ds.synchronizer.XSKODataSynchronizer.synchronizeResource(XSKODataSynchronizer.java:248) ~[xsk-modules-engines-xsodata-0.13.8.jar:na]
	... 13 common frames omitted
```

**Comment by dpanayotov** [comment]
Exception logged because calculation view does not exist.
Check if error handling can be improved and log message adjusted to reflect actual reason

**Comment by mvmanov** [comment]
It happens when the type of the artifact is CALCULATED
