### ISSUE TITLE
[XSOData] Null JoinPropertyList

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1804]
When synchronizing XSOData from the new products sample - https://github.com/SAP/xsk/blob/products-sample-next/samples/products/odata/Products.xsodata the following exception occurs:
```
2022-07-21 08:09:41.020 [ERROR] [pool-3168-thread-1] o.e.d.c.s.api.AbstractSynchronizer - Resource [/registry/public/products/protected/Products.xsodata] skipped due to an error: java.lang.NullPointerException: Cannot invoke "com.sap.xsk.parser.xsodata.core.HdbxsodataParser$JoinpropertieslistContext.propertylist()" because the return value of "com.sap.xsk.parser.xsodata.core.HdbxsodataParser$EndrefContext.joinpropertieslist()" is null
org.eclipse.dirigible.core.scheduler.api.SynchronizationException: java.lang.NullPointerException: Cannot invoke "com.sap.xsk.parser.xsodata.core.HdbxsodataParser$JoinpropertieslistContext.propertylist()" because the return value of "com.sap.xsk.parser.xsodata.core.HdbxsodataParser$EndrefContext.joinpropertieslist()" is null
	at com.sap.xsk.xsodata.ds.synchronizer.XSKODataSynchronizer.synchronizeResource(XSKODataSynchronizer.java:239) ~[xsk-modules-engines-xsodata-0.19.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:113) ~[dirigible-core-scheduler-6.3.9.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:120) ~[dirigible-core-scheduler-6.3.9.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:120) ~[dirigible-core-scheduler-6.3.9.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeRegistry(AbstractSynchronizer.java:97) ~[dirigible-core-scheduler-6.3.9.jar:na]
	at com.sap.xsk.xsodata.ds.synchronizer.XSKODataSynchronizer.synchronizeRegistry(XSKODataSynchronizer.java:212) ~[xsk-modules-engines-xsodata-0.19.0-SNAPSHOT.jar:na]
	at com.sap.xsk.xsodata.ds.synchronizer.XSKODataSynchronizer.synchronize(XSKODataSynchronizer.java:110) ~[xsk-modules-engines-xsodata-0.19.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.synchronizer.OrderedSynchronizer.synchronize(OrderedSynchronizer.java:74) ~[dirigible-core-scheduler-6.3.9.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizerJob$1.run(AbstractSynchronizerJob.java:46) ~[dirigible-core-scheduler-6.3.9.jar:na]
	at org.eclipse.dirigible.commons.timeout.TimeLimited$1.call(TimeLimited.java:38) ~[dirigible-commons-timeout-6.3.9.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.NullPointerException: Cannot invoke "com.sap.xsk.parser.xsodata.core.HdbxsodataParser$JoinpropertieslistContext.propertylist()" because the return value of "com.sap.xsk.parser.xsodata.core.HdbxsodataParser$EndrefContext.joinpropertieslist()" is null
	at com.sap.xsk.parser.xsodata.custom.XSKHDBXSODATACoreListener.assembleBindingFromAssociationContext(XSKHDBXSODATACoreListener.java:284) ~[xsk-modules-parsers-xsodata-0.19.0-SNAPSHOT.jar:na]
	at com.sap.xsk.parser.xsodata.custom.XSKHDBXSODATACoreListener.exitAssociation(XSKHDBXSODATACoreListener.java:208) ~[xsk-modules-parsers-xsodata-0.19.0-SNAPSHOT.jar:na]
	at com.sap.xsk.parser.xsodata.core.HdbxsodataParser$AssociationContext.exitRule(HdbxsodataParser.java:3012) ~[xsk-modules-parsers-xsodata-0.19.0-SNAPSHOT.jar:na]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:62) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:38) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36) ~[antlr4-runtime-4.10.1.jar:4.10.1]
	at com.sap.xsk.xsodata.ds.service.XSKODataParser.parseXSODataArtifact(XSKODataParser.java:113) ~[xsk-modules-engines-xsodata-0.19.0-SNAPSHOT.jar:na]
	at com.sap.xsk.xsodata.ds.service.XSKODataCoreService.parseOData(XSKODataCoreService.java:104) ~[xsk-modules-engines-xsodata-0.19.0-SNAPSHOT.jar:na]
	at com.sap.xsk.xsodata.ds.synchronizer.XSKODataSynchronizer.synchronizeResource(XSKODataSynchronizer.java:237) ~[xsk-modules-engines-xsodata-0.19.0-SNAPSHOT.jar:na]
	... 13 common frames omitted
```

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
