### ISSUE TITLE
[RealProject][Parser - HDBTABLE]  Property temporary is already declared

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#301]
```
table.schemaName  = "SAP_INO";
table.tableType   = ROWSTORE;
table.temporary   = true;
table.temporary   = true;
table.description = "Generic object id table";
table.columns = [
    {name = "ID"; sqlType = INTEGER; comment = "Object identifier";}
];
```

2021-07-05 08:33:57.194 [ERROR] [pool-113-thread-1] o.e.d.c.s.api.AbstractSynchronizer - Resource [/registry/public/**tt_object_id.hdbtable**] skipped due to an error: 

com.sap.xsk.parser.hdbtable.exceptions.XSKHDBTableDuplicatePropertyException: **Property temporary is already declared!
org.eclipse.dirigible.core.scheduler.api.SynchronizationException:** 

```
com.sap.xsk.parser.hdbtable.exceptions.XSKHDBTableDuplicatePropertyException: Property temporary is already declared!
        at com.sap.xsk.hdb.ds.facade.XSKHDBCoreFacade.handleResourceSynchronization(XSKHDBCoreFacade.java:98) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.synchronizer.XSKDataStructuresSynchronizer.synchronizeResource(XSKDataStructuresSynchronizer.java:367) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:109) ~[dirigible-core-scheduler-5.11.8.jar:na]
        at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeRegistry(AbstractSynchronizer.java:93) ~[dirigible-core-scheduler-5.11.8.jar:na]
        at com.sap.xsk.hdb.ds.synchronizer.XSKDataStructuresSynchronizer.synchronizeRegistry(XSKDataStructuresSynchronizer.java:352) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.synchronizer.XSKDataStructuresSynchronizer.synchronize(XSKDataStructuresSynchronizer.java:206) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizerJob$1.run(AbstractSynchronizerJob.java:53) ~[dirigible-core-scheduler-5.11.8.jar:na]
        at org.eclipse.dirigible.commons.config.timeout.TimeLimited$1.call(TimeLimited.java:38) ~[dirigible-commons-config-5.11.8.jar:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.sap.xsk.parser.hdbtable.exceptions.XSKHDBTableDuplicatePropertyException: Property temporary is already declared!
        at com.sap.xsk.parser.hdbtable.custom.XSKHDBTABLECoreVisitor.checkPropertyDeclarationUniqueness(XSKHDBTABLECoreVisitor.java:301) ~[xsk-modules-parsers-hdbtable-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.parser.hdbtable.custom.XSKHDBTABLECoreVisitor.visitHdbtableDefinition(XSKHDBTABLECoreVisitor.java:55) ~[xsk-modules-parsers-hdbtable-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.parser.hdbtable.custom.XSKHDBTABLECoreVisitor.visitHdbtableDefinition(XSKHDBTABLECoreVisitor.java:27) ~[xsk-modules-parsers-hdbtable-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.parser.hdbtable.core.HdbtableParser$HdbtableDefinitionContext.accept(HdbtableParser.java:101) ~[xsk-modules-parsers-hdbtable-0.7.0-SNAPSHOT.jar:na]
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:44) ~[antlr4-runtime-4.3.jar:4.3]
        at com.sap.xsk.hdb.ds.parser.hdbtable.XSKTableParser.parseHanaXSClassicContent(XSKTableParser.java:95) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.parser.hdbtable.XSKTableParser.parse(XSKTableParser.java:69) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.parser.hdbtable.XSKTableParser.parse(XSKTableParser.java:48) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.service.parser.XSKCoreParserService.parseDataStructure(XSKCoreParserService.java:34) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.facade.XSKHDBCoreFacade.handleResourceSynchronization(XSKHDBCoreFacade.java:89) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        ... 11 common frames omitted

```

**SOLUTION: document that the Parser do not allow duplicates. Wiki doc: https://github.com/SAP/xsk/wiki/Parser-hdbtable
No fix is needed**

**Comment by antoanetamh** [comment]
Documentation is updated: https://github.com/SAP/xsk/wiki/Parser-hdbtable
