### ISSUE TITLE
[RealProject][Parser - HDBTI] No enum constant org.eclipse.dirigible.database.sql.DataType.NCLOB

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#302]
Dirigible issue: https://github.com/eclipse/dirigible/issues/927

```
table.schemaName = "SAP_INO";
table.tableType = COLUMNSTORE;
table.description = "Language dependend Text Module";
table.columns = [
    {name = "PACKAGE_ID";        sqlType = NVARCHAR; length = 256; nullable = false; comment = "Package where content is delivered from";},
    {name = "CODE";              sqlType = VARCHAR;  length = 500; nullable = false; comment = "Text Module Identifier";},
    {name = "ID";                sqlType = INTEGER;                nullable = true;  comment = "Human-readable identifier of language dependend Text Module";},
	{name = "TEXT_MODULE_CODE";  sqlType = VARCHAR;  length = 500; nullable = false; comment = "Template the language specific content belongs to. Foreign key to t_mail_template.code";},
	{name = "TEXT_MODULE_ID";    sqlType = INTEGER;                nullable = true;  comment = "ID of the template the language specific content belongs to.";},
	{name = "LANG";              sqlType = VARCHAR;  length = 5;   nullable = false; comment = "Language. Foreign key to t_lang.CODE";},
	{name = "TEXT_MODULE";       sqlType = NCLOB;                  nullable = true;  comment = "Text Module";},
	{name = "DEFAULT_TEXT";      sqlType = NVARCHAR; length = 100; nullable = true;  comment = "Default Text-Description for Text Module";},
    {name = "DEFAULT_LONG_TEXT"; sqlType = NVARCHAR; length = 300; nullable = true;  comment = "Default Long Text-Description for Text Module";},
	{name = "PLAIN_CODE";        sqlType = VARCHAR;  length = 100; nullable = true;  comment = "Code key without package and naming prefix for UI maintenance";},
	{name = "CREATED_AT";        sqlType = TIMESTAMP;              nullable = true;  comment = "Creation timestamp";},
    {name = "CREATED_BY_ID";     sqlType = INTEGER;                nullable = true;  comment = "Identity by which content has been created.";},
    {name = "CHANGED_AT";        sqlType = TIMESTAMP;              nullable = true;  comment = "Changed timestamp";},
    {name = "CHANGED_BY_ID";     sqlType = INTEGER;                nullable = true;  comment = "Identity by which content has been changed.";}
];
table.primaryKey.pkcolumns = ["PACKAGE_ID", "CODE"];
```
2021-07-05 08:34:08.617 [INFO ] [pool-113-thread-1] c.s.x.h.d.p.t.XSKTableCreateProcessor - Processing Create Table: "t_text_module_t_stage"

2021-07-05 08:34:08.618 [ERROR] [pool-113-thread-1] c.s.x.hdb.ds.facade.XSKHDBCoreFacade - **No enum constant org.eclipse.dirigible.database.sql.DataType.NCLOB**

```
java.lang.IllegalArgumentException: No enum constant org.eclipse.dirigible.database.sql.DataType.NCLOB
        at java.base/java.lang.Enum.valueOf(Enum.java:240) ~[na:na]
        at org.eclipse.dirigible.database.sql.DataType.valueOf(DataType.java:17) ~[dirigible-database-sql-5.11.8.jar:na]
        at com.sap.xsk.hdb.ds.processors.table.XSKTableEscapeService.escapeHDBTableColumnModel(XSKTableEscapeService.java:62) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.processors.table.XSKTableEscapeService.getDatabaseSpecificSQL(XSKTableEscapeService.java:51) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.processors.table.XSKTableCreateProcessor.execute(XSKTableCreateProcessor.java:53) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.processors.table.XSKTableCreateProcessor.execute(XSKTableCreateProcessor.java:29) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.service.manager.IXSKTableManagerService.createDataStructure(IXSKTableManagerService.java:74) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.service.manager.IXSKTableManagerService.createDataStructure(IXSKTableManagerService.java:30) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.facade.XSKHDBCoreFacade.updateEntities(XSKHDBCoreFacade.java:334) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at com.sap.xsk.hdb.ds.synchronizer.XSKDataStructuresSynchronizer.synchronize(XSKDataStructuresSynchronizer.java:207) ~[xsk-modules-engines-hdb-0.7.0-SNAPSHOT.jar:na]
        at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizerJob$1.run(AbstractSynchronizerJob.java:53) ~[dirigible-core-scheduler-5.11.8.jar:na]
        at org.eclipse.dirigible.commons.config.timeout.TimeLimited$1.call(TimeLimited.java:38) ~[dirigible-commons-config-5.11.8.jar:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]		

```

**Comment by antoanetamh** [comment]
Resolve eclipse/dirigible#927
