### ISSUE TITLE
XSK is not able to start

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#358]
Pulling the latest docker image and running it locally results into error.
```
docker run --name xsk --rm -p 8080:8080 dirigiblelabs/xsk:latest
```

Stack trace:
```java
2021-08-02 14:36:53.637 [ERROR] [localhost-startStop-1] o.e.d.commons.config.StaticObjects - Static object by key: xskTableImportArtifactDao is null
java.lang.Exception: Static object by key: xskTableImportArtifactDao is null
	at org.eclipse.dirigible.commons.config.StaticObjects.get(StaticObjects.java:59)
	at com.sap.xsk.hdbti.service.XSKHDBTICoreService.<init>(XSKHDBTICoreService.java:50)
	at com.sap.xsk.hdbti.processors.XSKHDBTIProcessor.<init>(XSKHDBTIProcessor.java:52)
	at com.sap.xsk.hdbti.module.XSKHdbtiModule.configure(XSKHdbtiModule.java:35)
	at org.eclipse.dirigible.commons.api.module.DirigibleModulesInstallerModule.configure(DirigibleModulesInstallerModule.java:74)
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initializeModules(DirigibleInitializer.java:79)
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initialize(DirigibleInitializer.java:56)
	at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:39)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ThuF** [comment]
Related to: https://github.com/eclipse/dirigible/issues/970
