### ISSUE TITLE
[Migration Tools] Flowable HANA database is not supported

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#483]
It seems that the HANA database is not supported by the Flowable BPMN engine. List of all supported databases could be found [here](https://flowable.com/open-source/docs/form/ch02-Configuration/#supported-databases).

Exception:
```java
o.e.d.b.f.s.BpmSynchronizer - Synchronizing process for BPMN files failed.
org.flowable.engine.common.api.FlowableException: couldn't deduct database type from database product name 'HDB'
	at org.flowable.engine.common.impl.AbstractEngineConfiguration.initDatabaseType(AbstractEngineConfiguration.java:370) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	at org.flowable.engine.common.impl.AbstractEngineConfiguration.initDataSource(AbstractEngineConfiguration.java:357) ~[flowable-engine-common-6.3.0.jar:6.3.0]
	at org.flowable.engine.impl.cfg.ProcessEngineConfigurationImpl.init(ProcessEngineConfigurationImpl.java:831) ~[flowable-engine-6.3.0.jar:6.3.0]
	at org.flowable.engine.impl.cfg.ProcessEngineConfigurationImpl.buildProcessEngine(ProcessEngineConfigurationImpl.java:798) ~[flowable-engine-6.3.0.jar:6.3.0]
	at org.eclipse.dirigible.bpm.flowable.BpmProviderFlowable.getProcessEngine(BpmProviderFlowable.java:140) ~[dirigible-bpm-flowable-5.12.16.jar:na]
	at org.eclipse.dirigible.bpm.flowable.synchronizer.BpmSynchronizer.updateProcessEngine(BpmSynchronizer.java:256) ~[dirigible-bpm-flowable-5.12.16.jar:na]
	at org.eclipse.dirigible.bpm.flowable.synchronizer.BpmSynchronizer.synchronize(BpmSynchronizer.java:85) ~[dirigible-bpm-flowable-5.12.16.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizerJob$1.run(AbstractSynchronizerJob.java:52) ~[dirigible-core-scheduler-5.12.16.jar:na]
	at org.eclipse.dirigible.commons.timeout.TimeLimited$1.call(TimeLimited.java:38) ~[dirigible-commons-timeout-5.12.16.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
```

**Comment by ThuF** [comment]
Related to: https://github.com/eclipse/dirigible/issues/1110

**Comment by delchev** [comment]
Let's use the local system database for flowable needs, it does not need to be HANA

**Comment by ThuF** [comment]
Workaround would be to set the `DIRIGIBLE_FLOWABLE_USE_DEFAULT_DATABASE` environment variable to `false`.

**Comment by ThuF** [comment]
Fixed with:
- https://github.com/SAP/xsk/commit/e4d6c52356b1abaeeed300564738ad18995bc72e
- https://github.com/eclipse/dirigible/commit/5aef909b4401065e55af49f8e4e195339784a1a5
