### ISSUE TITLE
[IDE] Not able to publish *.xsodata files on save

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#490]
### Impact
I'm not able to **auto-publish** `*.xsodata` files on save.

### Issue
The following request get's wrongly redirected to the OData handler:

```
http://localhost:8080/services/v4/ide/publisher/request/workspace/products/odata/Products.xsodata
```

![Screenshot 2021-09-10 at 19 03 38](https://user-images.githubusercontent.com/4092083/132883539-0d338381-92c5-40a0-841e-4e981b186695.png)

```json
{
   "error":{
      "code":null,
      "message":{
         "lang":"en-US",
         "value":"The request dispatcher does not allow the HTTP method used for the request."
      }
   }
}
```

Stacktrace:
```java
o.e.d.e.o.s.p.DefaultSQLProcessor - The request dispatcher does not allow the HTTP method used for the request.
org.apache.olingo.odata2.api.exception.ODataMethodNotAllowedException: The request dispatcher does not allow the HTTP method used for the request.
	at org.apache.olingo.odata2.core.ODataRequestHandler.validateUriMethod(ODataRequestHandler.java:233) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.ODataRequestHandler.validateMethodAndUri(ODataRequestHandler.java:215) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.ODataRequestHandler.handle(ODataRequestHandler.java:112) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.rest.ODataSubLocator.handle(ODataSubLocator.java:164) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.rest.ODataSubLocator.handlePost(ODataSubLocator.java:86) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[cxf-rt-frontend-jaxrs-3.4.2.jar:3.4.2]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:285) ~[cxf-rt-frontend-jaxrs-3.4.2.jar:3.4.2]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[cxf-rt-frontend-jaxrs-3.4.2.jar:3.4.2]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) ~[servlet-api.jar:na]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
        ...
```

### Proposed solution

Requests to `/services/v4/ide/publisher` should be ignored by the [XSODataForwardFilter](https://github.com/SAP/xsk/blob/main/modules/engines/engine-xsodata/src/main/java/com/sap/xsk/xsodata/ds/filter/XSODataForwardFilter.java).

**Comment by ThuF** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/7148b8b5d10b4e3e9aa3d5474ebe6d26feaf49df
