### ISSUE TITLE
[Parsers] Fix *.xsaccess

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#550]
As commented by @aihanrashidov:

Parsing issues with the `.xsaccess` artifact. The error is related to the parsing of the `authentication` key as specified in the issue when parsing a json like this:
```
{
  "exposed":true,
  "authentication":[{"method":"LogonTicket"},{"method":"Basic"}]
}
```
The value can be an array of multiple authentication methods but the parser is expecting only one.

Related to: #441

**Comment by ThuF** [comment]
Exception:
```java
o.e.d.c.s.api.AbstractSynchronizer - Resource [see below...] skipped due to an error: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 6 column 21
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 6 column 21
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176) ~[gson-2.2.4.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[gson-2.2.4.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.2.4.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[gson-2.2.4.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:741) ~[gson-2.2.4.jar:na]
	at com.sap.xsk.xsaccess.ds.model.access.XSKAccessArtifact.parse(XSKAccessArtifact.java:27) 
```

**test.xsaccess**:
```json
{
	"cache_control" : "must-revalidate",
	"enable_etags" : true,
	"exposed": true,
	"prevent_xsrf" : true,
	"authentication": [{
		"method": "Form"
	}],
	"headers": {
		"enabled": true,
		"customHeaders": [
			{ "name":"X-Frame-Options","value":"SAMEORIGIN"},
			{ "name":"X-Content-Type-Options","value":"nosniff"},
			{ "name":"X-XSS-Protection","value":"1; mode=block"}
		]
	},
	"default_connection" : "a.b.c.setupDU.restricted.lib::User"
}
```

**Comment by dpanayotov** [comment]
Related to #31
