### ISSUE TITLE
[Parsers] IndexOutOfBoundsException at XSKJobToXSKJobDefinitionTransformer 

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#79]
```2021-02-24 14:00:23.051 [ERROR] [pool-4-thread-1] o.e.d.c.s.api.AbstractSynchronizer - Resource [see below...] skipped due to an error: Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[na:na]
	at java.base/java.util.Objects.checkIndex(Objects.java:372) ~[na:na]
	at java.base/java.util.ArrayList.get(ArrayList.java:458) ~[na:na]
	at com.sap.xsk.xsjob.ds.tronsformer.XSKJobToXSKJobDefinitionTransformer.transform(XSKJobToXSKJobDefinitionTransformer.java:46)
```

```
{
"description": "Scheduler for threading feature",
"action":"a.b.c:s.xsjs::execute",
"schedules":[

]
} 

```

**Comment by LiliyaLazarova** [comment]
Fixed with https://github.com/SAP/xsk/commit/01c8a30bff519f30988e33e34984cfd4f7c2b9f8 and https://github.com/SAP/xsk/pull/260
