### ISSUE TITLE
[Parsers] Expected BEGIN_OBJECT but was BEGIN_ARRAY in XSKAccessArtifact

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#80]
```
2021-02-24 14:00:33.393 [ERROR] [pool-8-thread-1] o.e.d.c.s.api.AbstractSynchronizer - Resource [see below...] skipped due to an error: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 6 column 21
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 6 column 21
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176) ~[gson-2.2.4.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93) ~[gson-2.2.4.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172) ~[gson-2.2.4.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[gson-2.2.4.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:741) ~[gson-2.2.4.jar:na]
	at com.sap.xsk.xsaccess.ds.model.access.XSKAccessArtifact.parse(XSKAccessArtifact.java:27) 
```

```
{
	"cache_control" : "must-revalidate",
	"enable_etags" : true,
	"exposed": true,
	"prevent_xsrf" : true,
	"authentication": [{
		"method": "Form"
	}],
	"headers": {
		"enabled": true,
		"customHeaders": [
			{ "name":"X-Frame-Options","value":"SAMEORIGIN"},
			{ "name":"X-Content-Type-Options","value":"nosniff"},
			{ "name":"X-XSS-Protection","value":"1; mode=block"}
		]
	},
	"default_connection" : "a.b.c.setupDU.restricted.lib::User"
}
```

**Comment by ThuF** [comment]
Related to: https://github.com/SAP/xsk/issues/31

**Comment by aihanrashidov** [comment]
The parsing of `.xsaccess` artifacts has been temporarily disabled until the parser is fixed due to not properly parsing the `authentication` values. 
Related issues - #441 #550

**Comment by ThuF** [comment]
Progress to be tracked here: https://github.com/SAP/xsk/issues/550
