### ISSUE TITLE
[Parsers] All the Privileges to be processed prior Access artifacts

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#81]
```
2021-02-24 14:00:33.867 [ERROR] [pool-8-thread-1] o.e.d.c.s.api.AbstractSynchronizer - Resource [...] skipped due to an error: com.sap.xsk.xsaccess.ds.api.XSKAccessException: com.sap.xsk.xsaccess.ds.api.XSKPrivilegeException: No XSK Privilege found with name: {sap.sports.imp.api.downloadQueue::fetch}
org.eclipse.dirigible.core.scheduler.api.SynchronizationException: com.sap.xsk.xsaccess.ds.api.XSKAccessException: com.sap.xsk.xsaccess.ds.api.XSKPrivilegeException: No XSK Privilege found with name: {a.b.c.downloadQueue::fetch}
	at com.sap.xsk.xsaccess.ds.synchronizer.XSKSecuritySynchronizer.synchronizeAccess(XSKSecuritySynchronizer.java:256) ~[xsk-modules-engines-core-0.2.0-SNAPSHOT.jar:na]
	at com.sap.xsk.xsaccess.ds.synchronizer.XSKSecuritySynchronizer.synchronizeResource(XSKSecuritySynchronizer.java:295) ~[xsk-modules-engines-core-0.2.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.api.AbstractSynchronizer.synchronizeCollection(AbstractSynchronizer.java:109) ~[dirigible-core-scheduler-5.8.1.jar:na]
```

**Comment by ThuF** [comment]
Related to: https://github.com/SAP/xsk/issues/550

**Comment by dpanayotov** [comment]
Related to #31
