### ISSUE TITLE
[Parsers] StringIndexOutOfBoundsException at XSKHDBTableFunctionParser

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#82]
```
Caused by: java.lang.StringIndexOutOfBoundsException: begin 312, end 54, length 1251
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[na:na]
	at java.base/java.lang.String.substring(String.java:1874) ~[na:na]
	at com.sap.xsk.hdb.ds.parser.hdbtablefunction.XSKHDBTableFunctionParser.extractTableFunctionNameFromContent(XSKHDBTableFunctionParser.java:31) ~[xsk-modules-engines-core-0.2.0-SNAPSHOT.jar:na]
	at com.sap.xsk.hdb.ds.parser.hdbtablefunction.XSKHDBTableFunctionParser.parse(XSKHDBTableFunctionParser.java:41) ~[xsk-modules-engines-core-0.2.0-SNAPSHOT.jar:na]
```

```
FUNCTION "DBADMIN"."a.b.c.function::Operation"
(
	aId NVARCHAR(32),
	bId NVARCHAR(32)
)
RETURNS TABLE
(
	...
)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER AS
BEGIN

 	...

END;
```

**Comment by LiliyaLazarova** [comment]
The bug was tested with different .hdbtablefunction definitions against Hana DB, but it wasn't possible to reproduce it and functions have been created in the DB, without hitting the exception mentioned in the description.
