### ISSUE TITLE
[XSOData] Create entity returns 500 but is created successfully

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#854]
**Describe the bug**
Create entity returns 500 but the record is created in HANA Cloud

> What version of the XSK are you using?
latest

**To Reproduce**
1. Import `products` sample
2. `POST http://localhost:8080/services/v4/web/products/odata/Products.xsodata/Orders` with body
```json
{
    "Id": "123",
}
```
3. See the following error returned
Status Code: 500
Body:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
    <code/>
    <message xml:lang="en">The metadata do not allow a null value for property 'CustomerName'.</message>
</error>
```
4. Go to the HANA Cloud db explorer and see that the record is created successfully

**Expected behavior**
As per [documentation](https://help.sap.com/viewer/52715f71adba4aaeb480d946c742d1f6/2.0.03/en-US/78746b112d794f459978eb55b20a8a6f.html#loio78746b112d794f459978eb55b20a8a6f__section_dgb_vyj_fn) - if neither `null` nor `not null` are specified the default value is `null` which means that `NULL` values are allowed. So I should not be getting an error

**Additional context**
The following exception is logged
```
org.apache.olingo.odata2.core.ep.EntityProviderProducerException: The metadata do not allow a null value for property 'CustomerSurname'.
	at org.apache.olingo.odata2.core.ep.producer.XmlPropertyEntityProducer.appendProperty(XmlPropertyEntityProducer.java:223) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.ep.producer.XmlPropertyEntityProducer.append(XmlPropertyEntityProducer.java:79) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.ep.producer.AtomEntryEntityProducer.appendPropertyNameValue(AtomEntryEntityProducer.java:659) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.ep.producer.AtomEntryEntityProducer.appendProperties(AtomEntryEntityProducer.java:636) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.ep.producer.AtomEntryEntityProducer.append(AtomEntryEntityProducer.java:135) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.ep.AtomEntityProvider.writeEntry(AtomEntityProvider.java:170) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.ep.ProviderFacadeImpl.writeEntry(ProviderFacadeImpl.java:129) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.api.ep.EntityProvider.writeEntry(EntityProvider.java:608) ~[olingo-odata2-api-2.0.11.jar:2.0.11]
	at org.eclipse.dirigible.engine.odata2.sql.processor.AbstractSQLProcessor.createEntity(AbstractSQLProcessor.java:497) ~[dirigible-odata-core-6.1.7.jar:na]
	at org.apache.olingo.odata2.core.Dispatcher.dispatch(Dispatcher.java:79) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.ODataRequestHandler.handle(ODataRequestHandler.java:131) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.rest.ODataSubLocator.handle(ODataSubLocator.java:164) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.rest.ODataSubLocator.handlePost(ODataSubLocator.java:86) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[cxf-rt-frontend-jaxrs-3.4.2.jar:3.4.2]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:285) ~[cxf-rt-frontend-jaxrs-3.4.2.jar:3.4.2]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[cxf-rt-frontend-jaxrs-3.4.2.jar:3.4.2]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[cxf-core-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[servlet-api.jar:na]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273) ~[cxf-rt-transports-http-3.4.2.jar:3.4.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316) ~[catalina.jar:8.5.43]
	at com.sap.xsk.xsodata.ds.filter.XSODataForwardFilter.doFilter(XSODataForwardFilter.java:47) ~[xsk-modules-engines-xsodata-0.12.0-SNAPSHOT.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at com.sap.xsk.xsaccess.ds.filter.XSKSecurityFilter.doFilter(XSKSecurityFilter.java:138) ~[xsk-modules-engines-xssecurity-0.12.0-SNAPSHOT.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364) ~[catalina.jar:8.5.43]
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:482) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:327) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:297) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.eclipse.jetty.servlets.QoSFilter.doFilter(QoSFilter.java:203) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.43]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) ~[catalina.jar:8.5.43]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.43]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.43]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:8.5.43]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.43]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.43]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: org.apache.olingo.odata2.api.edm.EdmSimpleTypeException: The metadata do not allow a null value.
	at org.apache.olingo.odata2.core.edm.AbstractSimpleType.valueToString(AbstractSimpleType.java:104) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	at org.apache.olingo.odata2.core.ep.producer.XmlPropertyEntityProducer.appendProperty(XmlPropertyEntityProducer.java:220) ~[olingo-odata2-core-2.0.11.jar:2.0.11]
	... 78 common frames omitted
```

Caused by #825

**Comment by dpanayotov** [comment]
fixed with #825
