### ISSUE TITLE
[Migration] Failing to list databases

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#980]
**Describe the bug**
When I enter my BTP credentials and try to list the databases nothing happens, but an exception is logged.

> What version of the XSK are you using?
latest

**To Reproduce**
Enter user credentials on the first step in the Migration perspective

**Expected behavior**
Process continues to next step

**Additional context**
Exception in stacktrace:

```
2022-01-11 07:56:18.157 [DEBUG] [http-nio-8080-exec-2] o.e.d.b.flowable.BpmProviderFlowable - Done starting a BPMN process by key: migrationProcess
2022-01-11 07:56:18.186 [ERROR] [http-nio-8080-exec-2] app.http.rs.controller - Serving resource[start-process], Verb[POST], Content-Type[application/json], Accept[application/json,text/plain,*/*] finished in error
2022-01-11 07:56:18.210 [ERROR] [http-nio-8080-exec-2] app.http.rs.controller - Serving request for Resource[{}], Method[{}], Content-Type[{}], Accept[{}] error handler threw error
Trying to use HTTP Response Facade without a valid Response
	at org.eclipse.dirigible.api.v3.http.HttpResponseFacade.flush(HttpResponseFacade.java:276)
	at <js> exports.flush(<eval>:53:1716-1775)
	at <js> HttpController.closeResponse(<eval>:909:35448-35463)
	at <js> this.execute(<eval>:843:32616-32664)
	at <js> __wrap__(<eval>:18-27:755-984)
	at <js> Module.loadScript(Unnamed:227:6108-6207)
	at <js> Module.load(Unnamed:205:5450-5474)
	at <js> :program(Unnamed:1:0-31)
	at org.graalvm.polyglot.Context.eval(Context.java:373)
	at org.eclipse.dirigible.engine.js.graalvm.processor.GraalVMJavascriptEngineExecutor.executeService(GraalVMJavascriptEngineExecutor.java:166)
	at org.eclipse.dirigible.engine.js.graalvm.processor.GraalVMJavascriptEngineExecutor.executeServiceModule(GraalVMJavascriptEngineExecutor.java:71)
	at org.eclipse.dirigible.engine.js.processor.DefaultJavascriptEngineExecutor.executeServiceModule(DefaultJavascriptEngineExecutor.java:64)
	at org.eclipse.dirigible.engine.js.processor.JavascriptEngineProcessor.executeService(JavascriptEngineProcessor.java:40)
	at org.eclipse.dirigible.engine.js.service.JavascriptEngineRestService.executeJavascriptServiceGet(JavascriptEngineRestService.java:70)
	at org.eclipse.dirigible.engine.js.service.JavascriptEngineRestService.executeJavascriptServicePost(JavascriptEngineRestService.java:91)
	at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.sap.xsk.xsaccess.ds.filter.XSKSecurityFilter.doFilter(XSKSecurityFilter.java:179)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.eclipse.dirigible.runtime.security.filter.SecurityFilter.doFilter(SecurityFilter.java:179)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.eclipse.dirigible.runtime.core.filter.HealthCheckFilter.doFilter(HealthCheckFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.eclipse.dirigible.runtime.core.filter.HttpContextFilter.doFilter(HttpContextFilter.java:57)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.sap.xsk.xsodata.ds.filter.XSODataForwardFilter.doFilter(XSODataForwardFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:482)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:327)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:297)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.eclipse.jetty.servlets.QoSFilter.doFilter(QoSFilter.java:203)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by host exception: org.eclipse.dirigible.commons.api.context.InvalidStateException: Trying to use HTTP Response Facade without a valid Response
```

Then requests continue to be made to `services/v4/js/ide-migration/server/migration/api/migration-rest-api.js/get-process` which return `500 Internal Server Error` and the following is logged:
```
2022-01-11 07:56:27.398 [ERROR] [http-nio-8080-exec-13] app.http.rs.controller - Serving resource[get-process], Verb[POST], Content-Type[application/json], Accept[application/json,text/plain,*/*] finished in error
org.eclipse.dirigible.api.v3.log.JSServiceException: undefined has no such function "toString"
```

Related to:
- https://github.com/SAP/xsk/issues/843

**Comment by vmutafov** [comment]
Fixed with: https://github.com/eclipse/dirigible/commit/7668aee139479e127dbfd94d84be11a06066dab7

@ThuF @delchev Could we make a new Dirigible release?

**Comment by ThuF** [comment]
Release **6.1.16** triggered: https://github.com/eclipse/dirigible/actions/runs/1684218847

**Comment by ThuF** [comment]
@vmutafov Eclipse Dirigible version updated with https://github.com/SAP/xsk/commit/98b9d35120246bdcc0e6a8928988c043946b5b06, should we close the issue?

**Comment by vmutafov** [comment]
I’ll quickly test it and close if everything is ok

**Comment by vmutafov** [comment]
I've validated it's working with the new Dirigible release. Closing this issue now
