### ISSUE TITLE
Logs directory not found

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#981]
**Describe the bug**
An exception is logged when navigating the web ide

> What version of the XSK are you using?
latest

**To Reproduce**
1. Start XSK
2. Go to the workbench perspective
3. See exception in logs

**Expected behavior**
No exception is logged

**Additional context**
`../logs` seems to be the value of `DIRIGIBLE_OPERATIONS_LOGS_ROOT_FOLDER_DEFAULT` variable https://github.com/eclipse/dirigible/blob/master/modules/services/service-operations/src/main/java/org/eclipse/dirigible/runtime/operations/processor/LogsProcessor.java#L37 

Exception:
```
2022-01-11 09:35:32.009 [TRACE] [http-nio-8080-exec-7] app.http.rs.controller - Serving request for Resource[ide.css], Method[GET], Content-Type[[]], Accept[["text/css","*/*"]] finished
2022-01-11 09:35:32.134 [TRACE] [http-nio-8080-exec-3] app.http.rs.controller - Serving request for Resource[bootstrap.min.css], Method[GET], Content-Type[[]], Accept[["text/css","*/*"]] finished
2022-01-11 09:35:32.164 [TRACE] [http-nio-8080-exec-8] app.http.rs.controller - Serving request for Resource[bootstrap.min.css], Method[GET], Content-Type[[]], Accept[["text/css","*/*"]] finished
2022-01-11 09:35:32.741 [TRACE] [http-nio-8080-exec-4] app.http.rs.controller - Serving request for Resource[extensions], Method[GET], Content-Type[[]], Accept[["*/*"]] finished
2022-01-11 09:35:33.002 [ERROR] [http-nio-8080-exec-7] o.e.d.r.c.s.GeneralExceptionHandler - ../logs
java.nio.file.NoSuchFileException: ../logs
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432) ~[na:na]
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:472) ~[na:na]
	at org.eclipse.dirigible.runtime.operations.processor.LogsProcessor.list(LogsProcessor.java:46) ~[dirigible-service-operations-6.1.14.jar:na]
	at org.eclipse.dirigible.runtime.operations.service.LogsService.listLogs(LogsService.java:86) ~[dirigible-service-operations-6.1.14.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[cxf-rt-frontend-jaxrs-3.5.0.jar:3.5.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[cxf-rt-frontend-jaxrs-3.5.0.jar:3.5.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[cxf-core-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) ~[cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[servlet-api.jar:na]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[cxf-rt-transports-http-3.5.0.jar:3.5.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.eclipse.dirigible.runtime.core.filter.HealthCheckFilter.doFilter(HealthCheckFilter.java:57) ~[dirigible-service-core-6.1.14.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.eclipse.dirigible.runtime.core.filter.HttpContextFilter.doFilter(HttpContextFilter.java:57) ~[dirigible-service-core-6.1.14.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at com.sap.xsk.xsodata.ds.filter.XSODataForwardFilter.doFilter(XSODataForwardFilter.java:50) ~[xsk-modules-engines-xsodata-0.13.0-SNAPSHOT.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364) ~[catalina.jar:8.5.43]
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:482) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:327) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:297) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.eclipse.jetty.servlets.QoSFilter.doFilter(QoSFilter.java:203) ~[jetty-servlets-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.43]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) ~[catalina.jar:8.5.43]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.43]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.43]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:8.5.43]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) ~[tomcat-coyote.jar:8.5.43]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.43]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.43]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

**Comment by vmutafov** [comment]
Fixed with: https://github.com/SAP/xsk/commit/9a8628111db92c42408761432caf6114e66695ef
