### ISSUE TITLE
[Releng] Docker - Access Denied Exception

### ISSUE THREAD

**Issue by ThuF** [SAP/xsk#991]
**Cannot create directory**:
```java
2022-01-12 09:05:42.543 [ERROR] [localhost-startStop-1] o.e.d.c.api.helpers.FileSystemUtils - Cannot create directory '/usr/local/tomcat/target/dirigible/cms/dirigible/repository/root'.
java.io.IOException: Cannot create directory '/usr/local/tomcat/target/dirigible/cms/dirigible/repository/root'.
	at org.apache.commons.io.FileUtils.mkdirs(FileUtils.java:2200) ~[commons-io-2.11.0.jar:2.11.0]
	at org.apache.commons.io.FileUtils.forceMkdir(FileUtils.java:1383) ~[commons-io-2.11.0.jar:2.11.0]
	at org.eclipse.dirigible.commons.api.helpers.FileSystemUtils.createFolder(FileSystemUtils.java:257) ~[dirigible-commons-api-6.1.16.jar:na]
	at org.eclipse.dirigible.repository.fs.FileSystemRepository.initializeRepository(FileSystemRepository.java:188) ~[dirigible-repository-local-6.1.16.jar:na]
	at org.eclipse.dirigible.repository.fs.FileSystemRepository.createRepository(FileSystemRepository.java:147) ~[dirigible-repository-local-6.1.16.jar:na]
	at org.eclipse.dirigible.repository.fs.FileSystemRepository.<init>(FileSystemRepository.java:117) ~[dirigible-repository-local-6.1.16.jar:na]
	at org.eclipse.dirigible.repository.local.LocalRepository.<init>(LocalRepository.java:74) ~[dirigible-repository-local-6.1.16.jar:na]
	at org.eclipse.dirigible.cms.internal.CmsProviderInternal.<init>(CmsProviderInternal.java:41) ~[dirigible-cms-internal-6.1.16.jar:na]
	at org.eclipse.dirigible.cms.internal.CmsInternalModule.configure(CmsInternalModule.java:44) ~[dirigible-cms-internal-6.1.16.jar:na]
	at org.eclipse.dirigible.commons.api.module.DirigibleModulesInstallerModule.configure(DirigibleModulesInstallerModule.java:73) ~[dirigible-commons-api-6.1.16.jar:na]
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initializeModules(DirigibleInitializer.java:79) ~[dirigible-service-core-6.1.16.jar:na]
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initialize(DirigibleInitializer.java:56) ~[dirigible-service-core-6.1.16.jar:na]
	at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:39) ~[dirigible-service-core-6.1.16.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165) ~[catalina.jar:8.5.43]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719) ~[catalina.jar:8.5.43]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) ~[catalina.jar:8.5.43]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970) ~[catalina.jar:8.5.43]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841) ~[catalina.jar:8.5.43]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

**AccessDeniedException**:
```java
org.h2.message.DbException: Log file error: "/usr/local/tomcat/target/dirigible/h2/SystemDB.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/usr/local/tomcat/target/dirigible/h2"" [90062-206]" [90034-206]
org.h2.message.DbException: Log file error: "/usr/local/tomcat/target/dirigible/h2/SystemDB.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/usr/local/tomcat/target/dirigible/h2"" [90062-206]" [90034-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.TraceSystem.logWritingError(TraceSystem.java:294)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:315)
	at org.h2.message.TraceSystem.writeFile(TraceSystem.java:263)
	at org.h2.message.TraceSystem.write(TraceSystem.java:247)
	at org.h2.message.Trace.error(Trace.java:187)
	at org.h2.engine.Database.<init>(Database.java:395)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:260)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2337)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2323)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2056)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
	at org.eclipse.dirigible.database.api.wrappers.WrappedDataSource.getConnection(WrappedDataSource.java:132)
	at org.eclipse.dirigible.database.api.wrappers.WrappedDataSource.getConnection(WrappedDataSource.java:120)
	at org.eclipse.dirigible.core.scheduler.quartz.QuartzDatabaseLayoutInitializer.initialize(QuartzDatabaseLayoutInitializer.java:54)
	at org.eclipse.dirigible.core.scheduler.manager.SchedulerInitializer.initializeScheduler(SchedulerInitializer.java:150)
	at org.eclipse.dirigible.core.scheduler.manager.SchedulerInitializer.initialize(SchedulerInitializer.java:61)
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.startupScheduler(DirigibleInitializer.java:199)
	at org.eclipse.dirigible.runtime.core.initializer.DirigibleInitializer.initialize(DirigibleInitializer.java:65)
	at org.eclipse.dirigible.runtime.core.listener.DirigibleServletContextListener.contextInitialized(DirigibleServletContextListener.java:39)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Log file error: "/usr/local/tomcat/target/dirigible/h2/SystemDB.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/usr/local/tomcat/target/dirigible/h2"" [90062-206]" [90034-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 40 more
Caused by: org.h2.message.DbException: Error while creating file "/usr/local/tomcat/target/dirigible/h2" [90062-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:343)
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:80)
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:355)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:305)
	... 37 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error while creating file "/usr/local/tomcat/target/dirigible/h2" [90062-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 42 more
Caused by: java.nio.file.AccessDeniedException: /usr/local/tomcat/target/dirigible/h2
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
	at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:334)
	... 40 more
```
Related to:
- https://github.com/SAP/xsk/issues/988

**Comment by alexkuklin** [comment]
Will look into it.
